apiVersion: v1
kind: ConfigMap
metadata:
  name: app-react-next-config-map
  labels:
    app: app-react-next
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server{
        listen       80;
        server_name sitio-app.local;  # replace 'jenkins.example.com' with your server domain name
        root /usr/share/nginx/html;
        index index.html index.htm index.nginx-debian.html;
        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~ "^/static/[0-9a-fA-F]{8}\/(.*)$" {
            # rewrite all static files into requests to the root
            # E.g /static/12345678/css/something.css will become /css/something.css
            rewrite "^/static/[0-9a-fA-F]{8}\/(.*)" /$1 last;
        }

        # Optional: Serve other types of assets (images, etc.)
        location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
            expires max;
            log_not_found off;
        }
      }
    }
