apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-client-ns
resources:
- ingress.yaml
- deployment.yaml
- service.yaml
configMapGenerator:
- literals:
  - KEY=value
  name: app-react-next-map
labels:
- includeSelectors: true
  pairs:
    app: app-react-next
