kind: Service
apiVersion: v1
metadata:
  name: app-react-next-service
  labels:
    app: app-react-next
spec:
  selector:
    app: app-react-next
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
