apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement-demo
  namespace: default
spec:
  ipAddressPools:
  - first-pool-demo
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: minikube
  interfaces:
  - eth0
